# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a09bfafe7f2af2e9030d566e4e0aa39e480ac0c232607208b87e341f639a629352ff1dc45b68d4e1917e9df64baddd67a0bca5b9e7ed67c7ae135719084013a5

test:
  secret_key_base: b0147d98999510469dcbdd7c4aab075a89e9b473b004aeb3440ab6b5a1035f8572f860c9437b8057982777942ef9c8841af2c73fe448497b54888fbd16d59fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
